# fly.toml app configuration file generated for signature-collector on 2023-10-11T19:09:30-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "signature-collector"
primary_region = "mia"

[build]

[env]
  VUE_APP_API_BASE_URL = "https://signature-collector-be-rdfu-dev.fl0.io"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
